AWSTemplateFormatVersion: 2010-09-09
Description: CFT for Creating EC2 instance
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0eba6c58b7918d3a1"
      InstanceType: "t2.micro"
      KeyName: "aws_key1"
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet:
         - sg-0fd7bbd97695466c6
        SubnetId: subnet-07b54be49413e3641
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp3"
          Iops: "100"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update -y
          sudo apt install apache2 -y
          sudo ufw allow 'Apache'
          sudo systemctl enable apache2
          sudo systemctl start apache2